STOPWORDS = {
    "a",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "by",
    "for",
    "from",
    "in",
    "into",
    "is",
    "it",
    "of",
    "on",
    "or",
    "that",
    "the",
    "their",
    "this",
    "to",
    "using",
    "use",
    "via",
    "with",
    "we",
    "our",
    "based",
    "toward",
    "study",
    "approach",
    "paper",
    "method",
    "methods",
    "model",
    "models",
    "research",
    "problem",
    "results",
    "analysis",
    "system",
    "framework",
    "task",
    "tasks",
    "dataset",
    "datasets",
}

TASK_LEXICON = {
    "classification": ["classification", "classify", "分类"],
    "segmentation": ["segmentation", "segment", "分割", "语义分割"],
    "object detection": ["object detection", "detect", "检测", "目标检测"],
    "retrieval": ["retrieval", "information retrieval", "检索"],
    "summarization": ["summarization", "summary", "摘要生成", "总结"],
    "generation": ["generation", "generative", "生成"],
    "translation": ["translation", "machine translation", "翻译"],
    "question answering": ["question answering", "qa", "问答"],
    "recommendation": ["recommendation", "recommendation system", "推荐系统"],
    "forecasting": ["forecasting", "prediction", "预测", "时间序列预测"],
    "representation learning": ["representation learning", "embedding", "表征学习"],
    "report generation": ["report generation", "报告生成"],
}

METHOD_LEXICON = {
    "transformer": ["transformer", "attention", "自注意力"],
    "graph neural network": ["graph neural network", "gnn", "图神经网络"],
    "contrastive learning": ["contrastive learning", "对比学习"],
    "reinforcement learning": ["reinforcement learning", "强化学习"],
    "diffusion model": ["diffusion", "diffusion model", "扩散模型"],
    "large language model": ["large language model", "llm", "大语言模型"],
    "retrieval augmented generation": ["retrieval augmented generation", "rag", "检索增强生成"],
    "fine tuning": ["fine tuning", "finetuning", "微调"],
    "transfer learning": ["transfer learning", "迁移学习"],
    "multimodal learning": ["multimodal", "multi modal", "多模态"],
    "self supervised learning": ["self supervised", "self-supervised", "自监督"],
    "federated learning": ["federated learning", "联邦学习"],
}

DOMAIN_LEXICON = {
    "medical imaging": ["medical imaging", "医学影像", "radiology", "mri", "ct"],
    "natural language processing": ["natural language processing", "nlp", "自然语言处理"],
    "computer vision": ["computer vision", "视觉", "图像"],
    "speech processing": ["speech", "语音"],
    "bioinformatics": ["bioinformatics", "生物信息学", "genomics"],
    "recommendation system": ["recommendation system", "推荐系统"],
    "robotics": ["robotics", "机器人"],
    "time series": ["time series", "时间序列"],
    "education": ["education", "教育"],
    "finance": ["finance", "financial", "金融"],
}

DATASET_HINTS = {
    "imagenet": ["imagenet"],
    "cifar-10": ["cifar-10", "cifar10"],
    "cifar-100": ["cifar-100", "cifar100"],
    "ms coco": ["coco", "ms coco"],
    "squad": ["squad"],
    "mimic-cxr": ["mimic-cxr", "mimic cxr"],
    "mimic-iii": ["mimic-iii", "mimic iii"],
    "librispeech": ["librispeech"],
    "movielens": ["movielens"],
}

CHINESE_HINTS = {
    "多模态": "multimodal learning",
    "医学影像": "medical imaging",
    "图神经网络": "graph neural network",
    "大语言模型": "large language model",
    "检索增强生成": "retrieval augmented generation",
    "对比学习": "contrastive learning",
    "强化学习": "reinforcement learning",
    "时间序列": "time series",
    "推荐系统": "recommendation system",
    "目标检测": "object detection",
    "语义分割": "semantic segmentation",
    "分类": "classification",
    "生成": "generation",
    "检索": "retrieval",
    "问答": "question answering",
    "预测": "forecasting",
    "迁移学习": "transfer learning",
    "微调": "fine tuning",
    "自然语言处理": "natural language processing",
    "计算机视觉": "computer vision",
}
